import { NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/db'
import { canSendSOW } from '@/lib/sow-utils'
import { sendEmail } from '@/lib/email'

/**
 * Convert structured SOW JSON content to a standalone HTML document.
 */
function generateSOWHtml(content: any): string {
  const opp = content.opportunity || {}
  const sections: any[] = content.sections || []
  const attachments: any[] = content.attachments || []

  const sectionHtml = sections.map((s: any) => {
    const bullets = Array.isArray(s.bullets)
      ? `<ul style="margin:8px 0;padding-left:20px;">${s.bullets.map((b: string) => `<li style="margin-bottom:4px;color:#374151;">${escapeHtml(b)}</li>`).join('')}</ul>`
      : ''
    const details = s.details
      ? `<p style="margin:8px 0;color:#4b5563;font-size:14px;white-space:pre-wrap;">${escapeHtml(s.details)}</p>`
      : ''
    return `
      <div style="margin-bottom:24px;">
        <h2 style="font-size:16px;font-weight:700;color:#111827;margin:0 0 4px;">${escapeHtml(s.title)}</h2>
        ${s.summary ? `<p style="margin:0 0 8px;color:#6b7280;font-size:13px;">${escapeHtml(s.summary)}</p>` : ''}
        ${bullets}
        ${details}
      </div>`
  }).join('')

  const attachmentsHtml = attachments.length > 0
    ? `<div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;">
        <h2 style="font-size:14px;font-weight:600;color:#374151;margin-bottom:8px;">Referenced Documents</h2>
        <ul style="padding-left:20px;">${attachments.map((a: any) => `<li style="margin-bottom:4px;"><a href="${escapeHtml(a.url)}" style="color:#2563eb;">${escapeHtml(a.name)}</a></li>`).join('')}</ul>
      </div>`
    : ''

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>SOW — ${escapeHtml(opp.solicitationNumber || '')}</title></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:800px;margin:0 auto;padding:32px 24px;">
    <div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:24px;margin-bottom:24px;">
      <h1 style="font-size:20px;font-weight:700;color:#111827;margin:0 0 12px;">${escapeHtml(opp.title || 'Scope of Work')}</h1>
      <table style="font-size:13px;color:#374151;border-collapse:collapse;">
        ${opp.solicitationNumber ? `<tr><td style="padding:2px 12px 2px 0;font-weight:600;">Solicitation</td><td>${escapeHtml(opp.solicitationNumber)}</td></tr>` : ''}
        ${opp.agency ? `<tr><td style="padding:2px 12px 2px 0;font-weight:600;">Agency</td><td>${escapeHtml(opp.agency)}</td></tr>` : ''}
        ${opp.responseDeadline ? `<tr><td style="padding:2px 12px 2px 0;font-weight:600;">Deadline</td><td>${escapeHtml(opp.responseDeadline)}</td></tr>` : ''}
        ${opp.setAside ? `<tr><td style="padding:2px 12px 2px 0;font-weight:600;">Set-Aside</td><td>${escapeHtml(opp.setAside)}</td></tr>` : ''}
        ${opp.naicsCode ? `<tr><td style="padding:2px 12px 2px 0;font-weight:600;">NAICS</td><td>${escapeHtml(opp.naicsCode)}</td></tr>` : ''}
        ${opp.placeOfPerformance ? `<tr><td style="padding:2px 12px 2px 0;font-weight:600;">Location</td><td>${escapeHtml(opp.placeOfPerformance)}</td></tr>` : ''}
      </table>
    </div>
    ${sectionHtml}
    ${attachmentsHtml}
    <p style="margin-top:32px;font-size:11px;color:#9ca3af;text-align:center;">Generated by USHER on ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>`
}

/**
 * Build a brief email body (text + HTML) summarizing the SOW.
 */
function generateSynopsis(content: any): { text: string; html: string } {
  const opp = content.opportunity || {}
  const sections: any[] = content.sections || []

  const lines: string[] = []
  lines.push(`SOW for: ${opp.title || 'Solicitation'}`)
  if (opp.solicitationNumber) lines.push(`Solicitation: ${opp.solicitationNumber}`)
  if (opp.agency) lines.push(`Agency: ${opp.agency}`)
  if (opp.responseDeadline) lines.push(`Deadline: ${opp.responseDeadline}`)
  lines.push('')

  // Include first few sections' key bullets
  for (const section of sections.slice(0, 4)) {
    if (section.bullets?.length) {
      lines.push(`${section.title}:`)
      for (const bullet of section.bullets.slice(0, 3)) {
        lines.push(`  - ${bullet}`)
      }
      lines.push('')
    }
  }

  lines.push('The full SOW is attached to this email.')

  const text = lines.join('\n')
  const html = `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;">
    <h2 style="font-size:16px;color:#111827;">SOW: ${escapeHtml(opp.title || 'Solicitation')}</h2>
    <table style="font-size:13px;color:#374151;margin-bottom:12px;">
      ${opp.solicitationNumber ? `<tr><td style="padding:2px 8px 2px 0;font-weight:600;">Solicitation</td><td>${escapeHtml(opp.solicitationNumber)}</td></tr>` : ''}
      ${opp.agency ? `<tr><td style="padding:2px 8px 2px 0;font-weight:600;">Agency</td><td>${escapeHtml(opp.agency)}</td></tr>` : ''}
      ${opp.responseDeadline ? `<tr><td style="padding:2px 8px 2px 0;font-weight:600;">Deadline</td><td>${escapeHtml(opp.responseDeadline)}</td></tr>` : ''}
    </table>
    ${sections.slice(0, 4).map(s => {
      if (!s.bullets?.length) return ''
      return `<p style="font-size:13px;font-weight:600;color:#374151;margin:8px 0 4px;">${escapeHtml(s.title)}</p>
        <ul style="margin:0;padding-left:16px;font-size:13px;color:#4b5563;">
          ${s.bullets.slice(0, 3).map((b: string) => `<li>${escapeHtml(b)}</li>`).join('')}
        </ul>`
    }).join('')}
    <p style="margin-top:16px;font-size:13px;color:#6b7280;">The full SOW is attached to this email.</p>
  </div>`

  return { text, html }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * POST /api/sows/[id]/send
 * Send SOW to subcontractor
 */
export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth()

    if (!session) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { id } = await params
    const body = await req.json()
    const { email, message } = body

    if (!email) {
      return NextResponse.json(
        { error: 'Email is required' },
        { status: 400 }
      )
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      )
    }

    // Fetch SOW
    const sow = await prisma.sOW.findUnique({
      where: { id },
      include: {
        opportunity: {
          select: {
            title: true,
            solicitationNumber: true,
          },
        },
      },
    })

    if (!sow) {
      return NextResponse.json(
        { error: 'SOW not found' },
        { status: 404 }
      )
    }

    // Check if SOW can be sent (must be APPROVED)
    if (!canSendSOW(sow.status)) {
      return NextResponse.json(
        { error: 'SOW must be approved before sending' },
        { status: 400 }
      )
    }

    // Check permissions - creator or ADMIN can send
    if (
      session.user.role !== 'ADMIN' &&
      sow.generatedById !== session.user.id
    ) {
      return NextResponse.json(
        { error: 'Forbidden - Only the creator or ADMIN can send this SOW' },
        { status: 403 }
      )
    }

    // Generate HTML document from SOW content
    const sowContent = sow.content as any
    const htmlDocument = generateSOWHtml(sowContent)
    const synopsis = generateSynopsis(sowContent)

    const solNum = sow.opportunity?.solicitationNumber || ''
    const title = sow.opportunity?.title || 'SOW'

    // Attempt to send email with SOW as attachment
    let emailWarning: string | undefined
    const emailResult = await sendEmail({
      to: email,
      subject: `SOW — ${solNum} — ${title}`,
      body: message ? `${message}\n\n---\n\n${synopsis.text}` : synopsis.text,
      html: message
        ? `<p style="font-family:sans-serif;font-size:14px;color:#374151;white-space:pre-wrap;">${escapeHtml(message)}</p><hr style="border:none;border-top:1px solid #e5e7eb;margin:16px 0;">${synopsis.html}`
        : synopsis.html,
      attachments: [{
        filename: sow.fileName || 'SOW.html',
        content: htmlDocument,
        contentType: 'text/html',
      }],
      googleAccessToken: (session as any).googleAccessToken,
      googleRefreshToken: (session as any).googleRefreshToken,
    })

    if (!emailResult.success) {
      emailWarning = `Email delivery failed: ${emailResult.error}. SOW marked as sent but email may not have been delivered.`
      console.warn(emailWarning)
    }

    // Update SOW with delivery information
    const updatedSow = await prisma.sOW.update({
      where: { id },
      data: {
        status: 'SENT',
        sentToEmail: email,
        sentAt: new Date(),
      },
      include: {
        opportunity: {
          select: {
            id: true,
            title: true,
            solicitationNumber: true,
          },
        },
        generatedBy: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    })

    // Create activity record
    await prisma.sOWActivity.create({
      data: {
        sowId: id,
        type: 'SENT',
        description: `SOW sent to ${email}`,
        userId: session.user.id,
        metadata: {
          email,
          message: message || null,
          sentBy: session.user.name || session.user.email,
          emailDelivered: emailResult.success,
          emailMessageId: emailResult.messageId || null,
        },
      },
    })

    return NextResponse.json({
      success: true,
      sow: updatedSow,
      message: `SOW sent successfully to ${email}`,
      ...(emailWarning ? { warning: emailWarning } : {}),
    })
  } catch (error) {
    console.error('Error sending SOW:', error)

    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    )
  }
}
